/**
 * This file is the entry point for the browser and is responsible
 * for hydrating the markup generated by the server in your server
 * entry module, however you can also initialize any other
 * client-side code here.
 *
 * This is the first piece of code that runs in the browser. You
 * can initialize client side libraries, add client only providers,
 * etc.
 */

import { startTransition, StrictMode } from "react";
import { hydrateRoot } from "react-dom/client";
import { HydratedRouter } from "react-router/dom";

startTransition(() => {
  hydrateRoot(
    document,
    <StrictMode>
      <HydratedRouter />
    </StrictMode>,
  );
});
