import type { Config } from "tailwindcss";

export default {
  content: ["./app/**/*.{js,jsx,ts,tsx}"],
  corePlugins: {},
  theme: {
    colors: {
      dark: "var(--colour-dark-primary)",
      light: "var(--colour-light-primary)",
      background: "var(--background-colour)",
      text: "var(--text-colour)",
      contentLink: "var(--content-link-colour)",
      contentLinkHover: "var(--content-link-colour-hover)",
      contentLinkUnderscore: "var(--link-underscore-colour)",
      contentLinkUnderscoreHover: "var(--link-underscore-colour-hover)",
      defaultLink: "var(--nav-link-colour)",
      defaultLinkHover: "var(--nav-link-colour-hover)",
      socialsLink: "var(--socials-link-colour)",
      socialsLinkHover: "var(--socials-link-hover)",
    },
    fontFamily: {
      default: "var(--font-family-default)",
      heading: "var(--font-family-heading)",
      display: "var(--font-family-display)",
      content: "var(--font-family-content)",
    },
    fontSize: {
      base: "62.5%",
      h1: "var(--font-size-h1)",
      h2: "var(--font-size-h2)",
      h3: "var(--font-size-h3)",
      h4: "var(--font-size-h4)",
      h5: "var(--font-size-h5)",
      large: "var(--font-size-large)",
      body: "var(--font-size-body)",
      small: "var(--font-size-small)",
    },
    lineHeight: {
      h1: "var(--line-height-h1)",
      h2: "var(--line-height-h2)",
      h3: "var(--line-height-h3)",
      h4: "var(--line-height-h4)",
      h5: "var(--line-height-h5)",
      subheading: "var(--line-height-subheading)",
      large: "var(--line-height-large)",
      body: "var(--line-height-body)",
      small: "var(--line-height-small)",
    },
    fontWeight: {
      h1: "var(--font-weight-h1)",
      h2: "var(--font-weight-h2)",
      h3: "var(--font-weight-h3)",
      h4: "var(--font-weight-h4)",
      h5: "var(--font-weight-h5)",
      body: "var(--font-weight-body)",
      strong: "var(--font-weight-social)",
    },
    letterSpacing: {
      h1: "var(--letter-spacing-h1)",
      h2: "var(--letter-spacing-h2)",
      h3: "var(--letter-spacing-h3)",
      h4: "var(--letter-spacing-h4)",
      h5: "var(--letter-spacing-h5)",
      large: "var(--letter-spacing-large)",
      body: "var(--letter-spacing-body)",
      small: "var(--letter-spacing-small)",
    },
    gap: {
      body: "var(--grid-gutter)",
    },
    spacing: {
      paragraph: "var(--spacing-between-paragraphs)",
      pageSection: "var(--spacing-page-section)",
      introSection: "var(--spacing-intro-section)",
      textToImage: "var(--spacing-text-to-image)",
      textToText: "var(--spacing-between-text)",
      headingToSubheading: "var(--spacing-heading-to-subheading)",
      h1: "var(--spacing-h1-to-text)",
      h2: "var(--spacing-h2-to-text)",
      row: "var(--spacing-footer-row)",
      0: "var(--lrd-size-0)",
      4: "var(--lrd-size-4)",
      8: "var(--lrd-size-8)",
      12: "var(--lrd-size-12)",
      16: "var(--lrd-size-16)",
      24: "var(--lrd-size-24)",
      32: "var(--lrd-size-32)",
      48: "var(--lrd-size-48)",
      64: "var(--lrd-size-64)",
      96: "var(--lrd-size-96)",
      128: "var(--lrd-size-128)",
      256: "var(--lrd-size-256)",
    },
    padding: {
      xs: "var(--lrd-padding-xs)",
      sm: "var(--lrd-padding-sm)",
      md: "var(--lrd-padding-md)",
      lg: "var(--lrd-padding-lg)",
      xl: "var(--lrd-padding-xl)",
    },
    transitionTimingFunction: {
      easeOut: "var(--ease-out)",
      easeOutSoft: "var(--ease-out-soft)",
    },
    transitionDuration: {
      100: "0.1s",
      125: "0.13s",
      150: "0.15s",
      200: "0.2s",
      250: "0.25s",
      350: "0.35s",
      500: "0.5s",
      550: "0.55s",
      650: "0.65s",
      750: "0.75s",
      1000: "1s",
    },
  },
  plugins: [],
} satisfies Config;
