[build]
command = "pnpm -F remix-app run build"
publish = "packages/remix-app/build/client"

[dev]
command = "npm run dev"
framework = "vite"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = 'public, max-age=31536000, s-maxage=2592000, immutable'
