import type { Config } from "tailwindcss";

export default {
    // content: ["./app/**/*.{js,jsx,ts,tsx}"],
    content: ["./app/**/{**,.client,.server}/**/*.{js,jsx,ts,tsx}"],
    theme: {
        colors: {
            dark: "var(--colour-dark-primary)",
            light: "var(--colour-light-primary)",
            background: "var(--background-colour)",
            text: "var(--text-colour)",
            contentLink: "var(--content-link-colour)",
            contentLinkHover: "var(--content-link-colour-hover)",
            contentLinkUnderscore: "var(--link-underscore-colour)",
            contentLinkUnderscoreHover: "var(--link-underscore-colour-hover)",
            defaultLink: "var(--nav-link-colour)",
            defaultLinkHover: "var(--nav-link-colour-hover)",
            socialsLink: "var(--socials-link-colour)",
            socialsLinkHover: "var(--socials-link-hover)",
        },
        fontFamily: {
            "family-default": "var(--font-family-default)",
            "family-heading": "var(--font-family-heading)",
            "family-display": "var(--font-family-display)",
            "family-content": "var(--font-family-content)",
        },
        fontSize: {
            base: "62.5%",
            h1: "var(--font-size-h1)",
            h2: "var(--font-size-h2)",
            h3: "var(--font-size-h3)",
            h4: "var(--font-size-h4)",
            h5: "var(--font-size-h5)",
            display: "var(--font-size-display)",
            large: "var(--font-size-large)",
            body: "var(--font-size-body)",
            small: "var(--font-size-small)",
        },
        lineHeight: {
            h1: "var(--line-height-h1)",
            h2: "var(--line-height-h2)",
            h3: "var(--line-height-h3)",
            h4: "var(--line-height-h4)",
            h5: "var(--line-height-h5)",
            subheading: "var(--line-height-subheading)",
            display: "var(--line-height-display)",
            large: "var(--line-height-large)",
            body: "var(--line-height-body)",
            small: "var(--line-height-small)",
        },
        fontWeight: {
            h1: "var(--font-weight-h1)",
            h2: "var(--font-weight-h2)",
            h3: "var(--font-weight-h3)",
            h4: "var(--font-weight-h4)",
            h5: "var(--font-weight-h5)",
            display: "var(--font-weight-display)",
            body: "var(--font-weight-body)",
            strong: "var(--font-weight-strong)",
        },
        letterSpacing: {
            h1: "var(--letter-spacing-h1)",
            h2: "var(--letter-spacing-h2)",
            h3: "var(--letter-spacing-h3)",
            h4: "var(--letter-spacing-h4)",
            h5: "var(--letter-spacing-h5)",
            display: "var(--letter-spacing-display)",
            large: "var(--letter-spacing-large)",
            body: "var(--letter-spacing-body)",
            small: "var(--letter-spacing-small)",
        },
        gap: {
            body: "var(--grid-gutter)",
        },
        spacing: {
            paragraph: "var(--spacing-between-paragraphs)",
            pageSection: "var(--spacing-page-section)",
            layoutSection: "var(--spacing-layout-section)",
            textToImage: "var(--spacing-text-to-image)",
            textToText: "var(--spacing-between-text)",
            headingToSubheading: "var(--spacing-heading-to-subheading)",
            h1: "var(--spacing-h1-to-text)",
            h2: "var(--spacing-h2-to-text)",
            row: "var(--spacing-footer-row)",
            0: "var(--lrd-size-0)",
            4: "var(--lrd-size-4)",
            8: "var(--lrd-size-8)",
            12: "var(--lrd-size-12)",
            16: "var(--lrd-size-16)",
            24: "var(--lrd-size-24)",
            32: "var(--lrd-size-32)",
            48: "var(--lrd-size-48)",
            64: "var(--lrd-size-64)",
            96: "var(--lrd-size-96)",
            128: "var(--lrd-size-128)",
            256: "var(--lrd-size-256)",
        },
        padding: {
            xs: "var(--lrd-padding-xs)",
            sm: "var(--lrd-padding-sm)",
            md: "var(--lrd-padding-md)",
            lg: "var(--lrd-padding-lg)",
            xl: "var(--lrd-padding-xl)",
        },
        transitionTimingFunction: {
            easeOut: "var(--ease-out)",
            easeOutSoft: "var(--ease-out-soft)",
        },
        transitionDuration: {
            100: "0.1s",
            125: "0.13s",
            150: "0.15s",
            200: "0.2s",
            250: "0.25s",
            350: "0.35s",
            500: "0.5s",
            550: "0.55s",
            650: "0.65s",
            750: "0.75s",
            1000: "1s",
        },
        extend: {
            keyframes: {
                "slide-up": {
                    "0%": { transform: "translateY(103%)" },
                    "100%": { transform: "translateY(0)" },
                },
                "fade-in": {
                    "0%": { opacity: "0" },
                    "100%": { opacity: "1" },
                },
                "asset-slide-up": {
                    "0%": { transform: "translateY(100%)" },
                    "100%": { transform: "translateY(0)" },
                },
                "asset-slide-down": {
                    "0%": {
                        transform: "translateY(-100%) scale3d(1.25, 1.25, 1)",
                    },
                    "100%": {
                        transform: "translateY(0) scaleX(1)",
                    },
                },
            },
            animation: {
                "slide-up": "slide-up 0.55s var(--ease-garret) forwards",
                "fade-in": "fade-in 0.65s var(--ease-out-soft) 0.2s forwards",
                "asset-slide-up":
                    "asset-slide-up 1s var(--ease-in-out-soft) 0.35s forwards",
                "asset-slide-down":
                    "asset-slide-down 1s var(--ease-in-out-soft) 0.35s forwards",
            },
            maxWidth: {
                body: "70rem",
            },
            margin: ({ theme }) => ({
                "grid-sm": theme("spacing.32"),
                "grid-md": theme("spacing.96"),
            }),
        },
    },
} satisfies Config;
