name: Merge

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  setup:
    name: Set up Environment
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-key.outputs.key }}
    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js and pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        run: pnpm lint

  types:
    name: Check Types
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run type checks
        run: pnpm types

  tests:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run unit tests
        run: pnpm test
