name: Merge

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js and pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Cache pnpm store and node_modules
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # Install dependencies
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

  lint:
    name: Lint Code
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js and pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Run linter
      - name: Run linter
        run: pnpm lint

  types:
    name: Check Types
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js and pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Run type checks
      - name: Run type checks
        run: pnpm types

  tests:
    name: Run Tests
    runs-on: ubuntu-22.04
    needs: install
    steps:
      - uses: actions/checkout@v4

      # Setup Node.js and pnpm
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Run unit tests
      - name: Run unit tests
        run: pnpm test
