name: Deploy to Netlify

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build, Lint, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # See https://github.com/pnpm/action-setup
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"

      # Install dependencies
      - name: Install dependencies
        run: pnpm install

      # Run linting
      - name: Run linter
        run: pnpm lint

      # Run types
      - name: Run types
        run: pnpm types

      # Run tests
      - name: Run unit tests
        run: pnpm test
